:concurrency: 5
:timeout: 25
:verbose: false
:queues:
  - default
  - evaluation
  - mailers

:scheduler:
  cleanup_failed_jobs:
    cron: '0 2 * * *'  # Daily at 2 AM
    class: CleanupFailedJobsJob

development:
  :concurrency: 2

test:
  :concurrency: 1

production:
  :concurrency: 10
  :timeout: 30