name: Ruby on Rails CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 20

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: rails_api_test
        ports:
          - "5432:5432"
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - "6379:6379"

    env:
      RAILS_ENV: test
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/rails_api_test
      REDIS_URL: redis://localhost:6379/0
      SECRET_KEY_BASE: test-secret-key-for-ci-tests-only
      OPENAI_API_KEY: test-api-key
      LLM_BASE_URL: https://api.openai.com
      LLM_MODEL: gpt-4
      EMBEDDING_MODEL: text-embedding-ada-002

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Install system dependencies (libpq)
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev

      - name: Verify bundle
        run: |
          bundle config set without 'production'
          bundle config set frozen false
          bundle install --jobs 4 --retry 3

      - name: Prepare database
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate
          bundle exec rails db:seed || true

      - name: Run RSpec
        run: |
          mkdir -p tmp
          bundle exec rspec --format progress --format RspecJunitFormatter --out tmp/rspec.xml || true

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rspec-report
          path: tmp/rspec.xml

  lint:
    name: Lint & Security
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Install linters
        run: |
          bundle config set without 'production'
          bundle config set frozen false
          bundle install --jobs 4 --retry 3

      - name: RuboCop
        run: |
          bundle exec rubocop --format progress --format json --out rubocop.json || true

      - name: RuboCop Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rubocop-report
          path: rubocop.json
          if-no-files-found: ignore

      - name: Brakeman
        run: |
          bundle exec brakeman -q -w2 -f json -o brakeman.json || true

      - name: Brakeman Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: brakeman-report
          path: brakeman.json
          if-no-files-found: ignore

      - name: Bundler Audit
        run: |
          bundle exec bundler-audit check --update --format json > bundler-audit.json || true

      - name: Bundler Audit Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bundler-audit-report
          path: bundler-audit.json
          if-no-files-found: ignore
